name: CI

on: [push, pull_request]

jobs:
  Pre-Commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - id: changed-files
      name: Get Changed Files
      uses: dorny/paths-filter@v2
      with:
        token: ${{ github.token }}
        list-files: shell
        filters: |
          repo:
            - added|modified:
              - '**'
    - name: Set Cache Key
      run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Check ALL Files On Branch
      uses: pre-commit/action@v2.0.0
      if: github.event_name != 'pull_request'
    - name: Check Changed Files On PR
      uses: pre-commit/action@v2.0.0
      if: github.event_name == 'pull_request'
      with:
        extra_args: --files ${{ steps.changed-files.outputs.repo_files }}


  Docs:
    runs-on: ubuntu-20.04
    needs: Pre-Commit

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Nox
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Doc Requirements
      run: |
        nox --force-color -e docs --install-only

    - name: Build Docs
      env:
        SKIP_REQUIREMENTS_INSTALL: YES
      run: |
        nox --force-color -e docs


  Windows:
    runs-on: windows-latest
    needs: Pre-Commit

    timeout-minutes: 40

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
        pytest-version:
          - "~=6.0.0"
          - "~=6.1.0"
          - "<=7.0.0"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Nox
      run: |
        python -m pip install --upgrade pip
        pip install nox 'pytest${{ matrix.pytest-version }}'

    - name: Gather CodeCov Info
      if: always()
      id: codecov-info
      shell: bash
      run: |
        echo ::set-output name=flag-python-version::$(python -c "import sys; print('Py{}{}'.format(*sys.version_info))")
        echo ::set-output name=flag-pytest-version::$(python -c "import pytest; print('PyTest{}{}'.format(*pytest.__version__.split('.')))")
        echo ::set-output name=flag-runner-os::$(python -c "print('${{ runner.os }}'.replace('-latest', ''))")
        echo ::set-output name=uploader-url::$(python -c "print('https://uploader.codecov.io/latest/codecov.exe')")

    - name: Create CodeCov Flags
      if: always()
      id: codecov
      shell: bash
      run: |
        echo ::set-output name=flags::$(python -c "print(','.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")
        echo ::set-output name=report-name::$(python -c "print('-'.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")

    - name: Install Test Requirements
      shell: bash
      env:
        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
      run: |
        export PATH="/C/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x64;$PATH"
        nox --force-color -e tests-${{ matrix.python-version }} --install-only

    - name: Test
      id: run-tests
      shell: bash
      env:
        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
        SKIP_REQUIREMENTS_INSTALL: YES
      run: |
        export PATH="/C/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x64;$PATH"
        nox --force-color -e tests-${{ matrix.python-version }} -- -vv tests/

    - name: Upload Project Code Coverage
      if: always()
      shell: bash
      env:
        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},src
        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-src
        REPORT_PATH: artifacts/coverage-project.xml
      run: |
        if [ ! -f codecov-uploader ]; then
            n=0
            until [ "$n" -ge 5 ]
            do
            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to download uploader"
            exit 1
        fi
        if [ -f codecov-uploader ]; then
            chmod +x codecov-uploader
            n=0
            until [ "$n" -ge 5 ]
            do
            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to upload codecov stats"
            exit 1
        fi

    - name: Upload Tests Code Coverage
      if: always()
      shell: bash
      env:
        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},tests
        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-tests
        REPORT_PATH: artifacts/coverage-tests.xml
      run: |
        if [ ! -f codecov-uploader ]; then
            n=0
            until [ "$n" -ge 5 ]
            do
            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to download uploader"
            exit 1
        fi
        if [ -f codecov-uploader ]; then
            chmod +x codecov-uploader
            n=0
            until [ "$n" -ge 5 ]
            do
            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to upload codecov stats"
            exit 1
        fi

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: runtests-${{ steps.codecov.outputs.report-name }}.log
        path: artifacts/runtests-*.log


  macOS:
    runs-on: macOS-latest
    needs: Pre-Commit

    timeout-minutes: 60

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
        pytest-version:
          - "~=6.0.0"
          - "~=6.1.0"
          - "<=7.0.0"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Nox
      run: |
        python -m pip install --upgrade pip
        pip install nox 'pytest${{ matrix.pytest-version }}'

    - name: Gather CodeCov Info
      if: always()
      id: codecov-info
      run: |
        echo ::set-output name=flag-python-version::$(python -c "import sys; print('Py{}{}'.format(*sys.version_info))")
        echo ::set-output name=flag-pytest-version::$(python -c "import pytest; print('PyTest{}{}'.format(*pytest.__version__.split('.')))")
        echo ::set-output name=flag-runner-os::$(python -c "print('${{ runner.os }}'.replace('-latest', ''))")
        echo ::set-output name=uploader-url::$(python -c "print('https://uploader.codecov.io/latest/codecov-macos')")

    - name: Create CodeCov Flags
      if: always()
      id: codecov
      run: |
        echo ::set-output name=flags::$(python -c "print(','.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")
        echo ::set-output name=report-name::$(python -c "print('-'.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")

    - name: Install Test Requirements
      env:
        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
      run: |
        nox --force-color -e tests-${{ matrix.python-version }} --install-only

    - name: Test
      id: run-tests
      env:
        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
        SKIP_REQUIREMENTS_INSTALL: YES
      run: |
        nox --force-color -e tests-${{ matrix.python-version }} -- -vv tests/

    - name: Upload Project Code Coverage
      if: always()
      shell: bash
      env:
        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},src
        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-src
        REPORT_PATH: artifacts/coverage-project.xml
      run: |
        if [ ! -f codecov-uploader ]; then
            n=0
            until [ "$n" -ge 5 ]
            do
            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to download uploader"
            exit 1
        fi
        if [ -f codecov-uploader ]; then
            chmod +x codecov-uploader
            n=0
            until [ "$n" -ge 5 ]
            do
            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to upload codecov stats"
            exit 1
        fi

    - name: Upload Tests Code Coverage
      if: always()
      shell: bash
      env:
        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},tests
        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-tests
        REPORT_PATH: artifacts/coverage-tests.xml
      run: |
        if [ ! -f codecov-uploader ]; then
            n=0
            until [ "$n" -ge 5 ]
            do
            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to download uploader"
            exit 1
        fi
        if [ -f codecov-uploader ]; then
            chmod +x codecov-uploader
            n=0
            until [ "$n" -ge 5 ]
            do
            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to upload codecov stats"
            exit 1
        fi

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: runtests-${{ steps.codecov.outputs.report-name }}.log
        path: artifacts/runtests-*.log


  Linux:
    runs-on: ubuntu-20.04
    needs: Pre-Commit

    timeout-minutes: 25

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        pytest-version:
          - "~=6.0.0"
          - "~=6.1.0"
          - "<=7.0.0"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Nox
      run: |
        python -m pip install --upgrade pip
        pip install nox 'pytest${{ matrix.pytest-version }}'

    - name: Gather CodeCov Info
      if: always()
      id: codecov-info
      run: |
        echo ::set-output name=flag-python-version::$(python -c "import sys; print('Py{}{}'.format(*sys.version_info))")
        echo ::set-output name=flag-pytest-version::$(python -c "import pytest; print('PyTest{}{}'.format(*pytest.__version__.split('.')))")
        echo ::set-output name=flag-runner-os::$(python -c "print('${{ runner.os }}'.replace('-latest', ''))")
        echo ::set-output name=uploader-url::$(python -c "print('https://uploader.codecov.io/latest/codecov-linux')")

    - name: Create CodeCov Flags
      if: always()
      id: codecov
      run: |
        echo ::set-output name=flags::$(python -c "print(','.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")
        echo ::set-output name=report-name::$(python -c "print('-'.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")

    - name: Install Test Requirements
      env:
        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
      run: |
        nox --force-color -e tests-${{ matrix.python-version }} --install-only

    - name: Test
      id: run-tests
      env:
        SKIP_REQUIREMENTS_INSTALL: YES
        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
      run: |
        nox --force-color -e tests-${{ matrix.python-version }} -- -vv tests/

    - name: Upload Project Code Coverage
      if: always()
      shell: bash
      env:
        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},src
        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-src
        REPORT_PATH: artifacts/coverage-project.xml
      run: |
        if [ ! -f codecov-uploader ]; then
            n=0
            until [ "$n" -ge 5 ]
            do
            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to download uploader"
            exit 1
        fi
        if [ -f codecov-uploader ]; then
            chmod +x codecov-uploader
            n=0
            until [ "$n" -ge 5 ]
            do
            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to upload codecov stats"
            exit 1
        fi

    - name: Upload Tests Code Coverage
      if: always()
      shell: bash
      env:
        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},tests
        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-tests
        REPORT_PATH: artifacts/coverage-tests.xml
      run: |
        if [ ! -f codecov-uploader ]; then
            n=0
            until [ "$n" -ge 5 ]
            do
            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to download uploader"
            exit 1
        fi
        if [ -f codecov-uploader ]; then
            chmod +x codecov-uploader
            n=0
            until [ "$n" -ge 5 ]
            do
            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
                rc=$?
                break
            fi
            rc=$?
            n=$((n+1))
            sleep 15
            done
        fi
        if [ $rc -ne 0 ]; then
            echo "Failed to upload codecov stats"
            exit 1
        fi

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: runtests-${{ steps.codecov.outputs.report-name }}.log
        path: artifacts/runtests-*.log
